<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN-Sandeep" name="Test1" tests="3" failures="1" timestamp="18 Jul 2017 04:04:00 GMT" time="4.718" errors="0">
  <testcase name="doLogin" time="2.281" classname="DD_TestCases.LoginTest">
    <skipped/>
  </testcase> <!-- doLogin -->
  <testcase name="doLogin" time="0.879" classname="DD_TestCases.LoginTest">
    <skipped/>
  </testcase> <!-- doLogin -->
  <testcase name="doLogin" time="0.846" classname="DD_TestCases.LoginTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.fail(Assert.java:100)
	at DD_TestCases.LoginTest.doLogin(LoginTest.java:39)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Test1 -->
